name: Measurement

on:
  push:
    branches:
      - elapsed
  workflow_dispatch:
jobs:
  measurement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run
        run: |
          ulimit -s unlimited
          python run.py
          cp result.md $GITHUB_STEP_SUMMARY