name: Measurement

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      run:
        type: string
        required: true
jobs:
  measurement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run
        run: |
          ulimit -s unlimited
          ${{inputs.run}}

      - name: Check
        run: |
          ls -l result.md
          cat result.md
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.name}}
          path: result.md
